ppwlab/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ppwstory1/', include('ppwstory1.urls')),
    path('ppwstory3/', include('ppwstory3.urls')),
    path('', include('ppwlabmain.urls'))
]

ppwlabmain/urls.py
from django.urls import include, path

from . import views

app_name = "ppwlabmain"

urlpatterns = [
    path('', views.index, name="index"),
]

ppwstory1/urls.py
from django.urls import include, path

from . import views

app_name = "ppwstory1"

urlpatterns = [
    path('', views.index, name="index"),
    path('profile/', views.viewProfile, name="profile")
]

ppwstory3/urls.py
from django.urls import include, path

from . import views

app_name = "ppwstory3"

urlpatterns = [
    path('', views.index, name="index"),
    path('profile/', views.profile, name="profile"),
    path('posts/', views.posts, name="posts"),
    path('posts/<int:number>', views.posts, name="posts")
]

ppwlabmain/models.py
from django.db import models

# Create your models here.

ppwstory1/models.py
from django.db import models

# Create your models here.

ppwstory3/models.py
from django.db import models

# Create your models here.

ppwlabmain/views.py
from django.shortcuts import render

def index(request):
    return render(request, "ppwlabmain/index.html")

ppwstory1/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'ppwstory1/index.html')

def viewProfile(request):
    return render(request, 'ppwstory1/profile.html')

ppwstory3/views.py
from django.http import Http404
from django.shortcuts import redirect, render, reverse
from django.template import TemplateDoesNotExist

from .apps import postdict, desdict

def index(request):
    return render(request, 'ppwstory3/index.html', {'postdict':postdict, "desdict": desdict, "range":range(1,len(postdict)+1)})

def profile(request):
    return render(request, 'ppwstory3/profile.html')

def posts(request, number=0):
    if (number==0):
        return redirect(reverse('ppwstory3:index'))
    else:
        return render(request, 'ppwstory3/posts/' + str(number) + ".html")

templates/base.html
<!DOCTYPE html>
<html>
    <head>
        {% block head %} {% endblock %}
    </head>
    <body>
        {% block body %} {% endblock %}
    </body>
</html>

templates/ppwlabmain/base.html
{% extends 'base.html' %}

{% block head %}
    <title>William's PPW Stories | {% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
{% endblock %}
{% block body %}
<div class="container-fluid">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'ppwlabmain:index' %}">William's PPW Stories</a>
    </nav>
    {% block content %}
    {% endblock %}
</div>
{% endblock %}

templates/ppwlabmain/index.html
{% extends 'ppwlabmain/base.html' %}

{% block title %} Main {% endblock %}
{% block content %}
<div class="container" style="margin: 20px auto;">
  <div class="row">
    <div class="col-sm" style="text-align: center; margin: 20px;">
      <a class="btn btn-primary" href="{% url 'ppwstory1:index' %}">Story 1</a>
    </div>
    <div class="col-sm" style="text-align: center; margin: 20px;">
      <a class="btn btn-primary" href="{% url 'ppwstory3:index' %}">Story 3</a>
    </div>
  </div>
</div>
{% endblock %}

templates/ppwstory1/base.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
    <title>PPW Story 1 | {% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'ppwstory1/style.css' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
{% endblock %}
{% block body %}
        <div class="navbar">
            <ul>
                <li><a href="{% url 'ppwstory1:index' %}">PPW Story 1</a></li>
                <li><a href="{% url 'ppwlabmain:index' %}">Return to Stories</a></li>
            </ul>
        </div>
        <div class="container">
            {% block content %}{% endblock %}
        </div>
        <div class="footer">
            <p>Created in 2020 by William</p>
        </div>
{% endblock %}

templates/ppwstory1/index.html
{% extends 'ppwstory1/base.html' %}
{% load static %}
{% block title %} Selamat Datang! {% endblock %}
{% block content %}
    <h2>Selamat Datang!</h2>
    <p>Selamat datang di web pertama saya!</p>
    <img alt="ProfilePic" src="{% static 'ppwstory1/profilepic.jpg' %}">
    <h2>William</h2>
    <p>Gemar mempelajari hal-hal baru</p>
    <div class="button">
        <a href="{% url 'ppwstory1:profile' %}">Tampilkan</a>
    </div>
{% endblock %}

templates/ppwstory1/profile.html
{% extends 'ppwstory1/base.html' %}
{% load static %}
{% block title %}Profile Saya{% endblock %}
{% block content %}
    <h2>Profile Saya</h2>
    <img alt="ProfilePic" src="{% static 'ppwstory1/profilepic.jpg' %}">
    <table>
        <tr>
            <td>Nama</td>
            <td>William</td>
        </tr> 
        <tr>
            <td>NPM</td>
            <td>1906350521</td>
        </tr>
        <tr>
            <td>Angkatan</td>
            <td>2019</td>
        </tr>
    </table>
    <h2>Hobi</h2>
    <p>Main game, Belajar hal baru</p>
    <h2>Deskripsi</h2>
    <p>
        Aku suka belajar hal-hal baru, namun aku cepat bosan. Sebelum kuliah, aku sudah belajar pemrograman,
        tapi sepertinya aku perlu belajar lebih banyak lagi.
    </p>
    <h2>Riwayat pendidikan</h2>
    <ul>
        <li>
            <p>S1 Ilmu Komputer, Universitas Indonesia (2019 - sekarang)</p>
        </li>
        <li>
            <p>SMA Negeri 2 Jakarta (2016 - 2019)</p>
        </li>
        <li>
            <p>SMP Kristen 2 BPK Penabur (2016 - 2013)</p>
        </li>
    </ul>
    <h2>
        Kontak
    </h2>
    <div class="contact">
        <a href="https://twitter.com/hori_75">
            <img alt="twitter" src="{% static 'ppwstory1/twitter.png' %}">
        </a>
        <a href="https://www.linkedin.com/in/william-8611851a0/">
            <img alt="linkedin" src="{% static 'ppwstory1/linkedin.png' %}" style="max-width: 59px; max-height: 59px;">
        </a>
    </div>
{% endblock %}

templates/ppwstory3/base.html
{% extends 'base.html' %}

{% load static %}
{% block head %}
    <title>PPW Story | {% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'ppwstory3/css/style.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
{% endblock %}
{% block body %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-3 sidebar">
                <img alt="William's photo" src="{% static 'ppwstory3/img/William.png' %}">
                <h2>William</h2>
                {% block sidebar %}
                {% endblock %}
                <div class="sidebar-button">
                    <ul>
                        {% block buttons %}
                        {% endblock %}
                        <li><a class="btn" href="{% url 'ppwlabmain:index' %}">Back to Stories</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-md-9 col-md-offset-3 content">
                <div class="content">
                    {% block content %}
                    {% endblock %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/ppwstory3/index.html
{% extends "ppwstory3/base.html" %}
{% load ppwstory3Customtags %}

{% block title %}Summary{% endblock %}

{% load static %}
{% block content %}
<h1>See What I have worked on...</h1>
<ul>
    {% for i in range %}
    <li>
        <div class="postpreview">
            <img alt="{{i}}" src="{% static 'ppwstory3/img/'|get_thumbnail:i %}">
            <div class="textbox">
                <h2><a href="{% url 'ppwstory3:posts' i %}">{{ postdict|get_item:i }}</a></h2>
                <p>{{ desdict|get_item:i }}</p>
            </div>
        </div>
    </li>
    {% endfor %}
</ul>
{% endblock %}
{% block sidebar %}
<p>Learning web development. Enthutiastic in learning new stuffs.</p>
{% endblock %}
{% block buttons %}
<li><a class="btn" href="{% url 'ppwstory3:profile' %}">View Profile</a></li>
{% endblock %}

templates/ppwstory3/post_base.html
{% extends "ppwstory3/base.html" %}

{% block content %}
<h1>{% block title %}{% endblock %}</h1>
<p>{% block date %}{% endblock %}</p>
<div class="post">
    {% block main %}
    {% endblock %}
</div>
{% endblock %}
{% block sidebar %}
<p>Learning web development. Enthutiastic in learning new stuffs.</p>
{% endblock %}
{% block buttons %}
<li><a class="btn" href="{% url 'ppwstory3:profile' %}">View Profile</a></li>
<li><a class="btn" href="{% url 'ppwstory3:index' %}">Main Page</a></li>
{% endblock %}

templates/ppwstory3/posts/1.html
{% extends "ppwstory3/post_base.html" %}

{% block title %}My experience in learning webdev{% endblock %}

{% block date %}3 Oktober 2020{% endblock %}

{% load static %}
{% block main %}
<img alt="Illustration of webdev" src="{% static 'ppwstory3/img/web-development.jpg' %}">
<div class="maintext">
    <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean non nibh ut turpis mattis interdum eget sagittis mi. Nulla tincidunt erat at justo hendrerit, eget aliquam augue suscipit. Suspendisse dapibus rhoncus volutpat. In at nulla sed eros posuere egestas. Nullam convallis justo massa, in auctor massa fringilla id. Vestibulum ullamcorper sem libero, at hendrerit tortor blandit vel. Aliquam commodo nec nisi vel tristique. Sed efficitur eleifend nulla condimentum vulputate. Cras non nisl lorem. In feugiat metus non mi scelerisque ornare. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vestibulum rhoncus sapien vitae leo lobortis, ut venenatis quam interdum. Nam interdum est scelerisque turpis faucibus rutrum.
    </p>
    <p>
        Fusce placerat leo vel iaculis ullamcorper. Aenean facilisis arcu tellus, ut vestibulum dolor ultrices vel. Aenean eget magna varius, suscipit lacus sit amet, iaculis nisl. Quisque pharetra, nisl non condimentum ornare, metus nunc viverra augue, vitae efficitur augue neque sit amet nunc. Curabitur purus tortor, convallis a rhoncus id, sagittis ac est. Sed lacus ex, viverra finibus tristique ut, commodo id mi. Maecenas venenatis fringilla quam a pulvinar. Vestibulum bibendum eu lectus vitae sollicitudin. Integer aliquam mattis accumsan. Nullam quis nisi arcu. Praesent est dui, egestas eget iaculis quis, pulvinar in lacus. Nulla suscipit molestie massa sit amet volutpat. Suspendisse convallis urna sed mauris bibendum, eget sodales purus vulputate. Aliquam suscipit vehicula interdum. Donec quam mi, facilisis nec dui id, accumsan feugiat eros.<br>
    </p> 
    <p>   
        Aenean tempor sit amet lacus id efficitur. Donec interdum velit neque, ac aliquam elit aliquam sagittis. Nullam est eros, ultrices in malesuada eu, ornare nec nulla. Quisque sed dapibus libero. Curabitur eget rutrum neque. Ut sed scelerisque felis. Nam id lorem sed arcu accumsan eleifend. Duis quis ex facilisis, tempus lectus sed, luctus nulla. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Suspendisse potenti. Proin sodales gravida tempor. Quisque urna dolor, eleifend a lorem vel, hendrerit aliquam mi. In faucibus ipsum at velit commodo, in luctus turpis eleifend.
    </p> 
    <p>
        Donec vel auctor nibh. Vivamus imperdiet nec metus id sodales. In non finibus nisi, vel pulvinar enim. Integer vel consectetur arcu. Aliquam erat volutpat. Curabitur ac ullamcorper elit, non laoreet eros. Donec id sollicitudin enim. Morbi id lorem nunc. Quisque consequat sodales turpis in dignissim. Sed at fringilla justo. Vivamus in risus bibendum, ornare est consequat, dignissim mauris.
    </p>
    <p> 
        Nunc pulvinar elit dolor, in hendrerit mi semper sit amet. Vestibulum ultricies egestas mi suscipit suscipit. Aliquam nec urna consequat, tempus mauris in, efficitur dolor. Donec ante odio, lacinia interdum leo sit amet, commodo lacinia diam. Duis pharetra nisl quis tortor congue imperdiet. Sed sit amet elit nibh. Aliquam eget pharetra justo. Quisque pulvinar quam porta mauris congue, eget vulputate augue consequat. Suspendisse ac dui quis erat euismod tincidunt id vel dolor. Fusce urna ligula, gravida vel mattis ut, iaculis eget lacus. Sed ultricies dolor ut ex tincidunt vehicula ut quis nisi. Morbi in dignissim felis. Maecenas ac mauris urna. Duis gravida eget diam ac accumsan. Donec a sem dignissim, rutrum enim at, porta neque.
    </p>
</div>
{% endblock %}

templates/ppwstory3/posts/2.html
{% extends "ppwstory3/post_base.html" %}

{% block title %}Random{% endblock %}

{% block date %}3 Oktober 2020{% endblock %}

{% load static %}
{% block main %}
<img alt="Illustration of random" src="{% static 'ppwstory3/img/matriks.png' %}">
<div class="maintext">
    <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean non nibh ut turpis mattis interdum eget sagittis mi. Nulla tincidunt erat at justo hendrerit, eget aliquam augue suscipit. Suspendisse dapibus rhoncus volutpat. In at nulla sed eros posuere egestas. Nullam convallis justo massa, in auctor massa fringilla id. Vestibulum ullamcorper sem libero, at hendrerit tortor blandit vel. Aliquam commodo nec nisi vel tristique. Sed efficitur eleifend nulla condimentum vulputate. Cras non nisl lorem. In feugiat metus non mi scelerisque ornare. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vestibulum rhoncus sapien vitae leo lobortis, ut venenatis quam interdum. Nam interdum est scelerisque turpis faucibus rutrum.
    </p>
    <p>
        Fusce placerat leo vel iaculis ullamcorper. Aenean facilisis arcu tellus, ut vestibulum dolor ultrices vel. Aenean eget magna varius, suscipit lacus sit amet, iaculis nisl. Quisque pharetra, nisl non condimentum ornare, metus nunc viverra augue, vitae efficitur augue neque sit amet nunc. Curabitur purus tortor, convallis a rhoncus id, sagittis ac est. Sed lacus ex, viverra finibus tristique ut, commodo id mi. Maecenas venenatis fringilla quam a pulvinar. Vestibulum bibendum eu lectus vitae sollicitudin. Integer aliquam mattis accumsan. Nullam quis nisi arcu. Praesent est dui, egestas eget iaculis quis, pulvinar in lacus. Nulla suscipit molestie massa sit amet volutpat. Suspendisse convallis urna sed mauris bibendum, eget sodales purus vulputate. Aliquam suscipit vehicula interdum. Donec quam mi, facilisis nec dui id, accumsan feugiat eros.<br>
    </p> 
    <p>   
        Aenean tempor sit amet lacus id efficitur. Donec interdum velit neque, ac aliquam elit aliquam sagittis. Nullam est eros, ultrices in malesuada eu, ornare nec nulla. Quisque sed dapibus libero. Curabitur eget rutrum neque. Ut sed scelerisque felis. Nam id lorem sed arcu accumsan eleifend. Duis quis ex facilisis, tempus lectus sed, luctus nulla. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Suspendisse potenti. Proin sodales gravida tempor. Quisque urna dolor, eleifend a lorem vel, hendrerit aliquam mi. In faucibus ipsum at velit commodo, in luctus turpis eleifend.
    </p> 
    <p>
        Donec vel auctor nibh. Vivamus imperdiet nec metus id sodales. In non finibus nisi, vel pulvinar enim. Integer vel consectetur arcu. Aliquam erat volutpat. Curabitur ac ullamcorper elit, non laoreet eros. Donec id sollicitudin enim. Morbi id lorem nunc. Quisque consequat sodales turpis in dignissim. Sed at fringilla justo. Vivamus in risus bibendum, ornare est consequat, dignissim mauris.
    </p>
    <p> 
        Nunc pulvinar elit dolor, in hendrerit mi semper sit amet. Vestibulum ultricies egestas mi suscipit suscipit. Aliquam nec urna consequat, tempus mauris in, efficitur dolor. Donec ante odio, lacinia interdum leo sit amet, commodo lacinia diam. Duis pharetra nisl quis tortor congue imperdiet. Sed sit amet elit nibh. Aliquam eget pharetra justo. Quisque pulvinar quam porta mauris congue, eget vulputate augue consequat. Suspendisse ac dui quis erat euismod tincidunt id vel dolor. Fusce urna ligula, gravida vel mattis ut, iaculis eget lacus. Sed ultricies dolor ut ex tincidunt vehicula ut quis nisi. Morbi in dignissim felis. Maecenas ac mauris urna. Duis gravida eget diam ac accumsan. Donec a sem dignissim, rutrum enim at, porta neque.
    </p>
</div>
{% endblock %}

templates/ppwstory3/posts/3.html
{% extends "ppwstory3/post_base.html" %}

{% block title %}Post3{% endblock %}

{% block date %}3 Oktober 2020{% endblock %}

{% load static %}
{% block main %}
<img alt="Illustration of random" src="{% static 'ppwstory3/img/matriks.png' %}">
<div class="maintext">
    <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean non nibh ut turpis mattis interdum eget sagittis mi. Nulla tincidunt erat at justo hendrerit, eget aliquam augue suscipit. Suspendisse dapibus rhoncus volutpat. In at nulla sed eros posuere egestas. Nullam convallis justo massa, in auctor massa fringilla id. Vestibulum ullamcorper sem libero, at hendrerit tortor blandit vel. Aliquam commodo nec nisi vel tristique. Sed efficitur eleifend nulla condimentum vulputate. Cras non nisl lorem. In feugiat metus non mi scelerisque ornare. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vestibulum rhoncus sapien vitae leo lobortis, ut venenatis quam interdum. Nam interdum est scelerisque turpis faucibus rutrum.
    </p>
    <p>
        Fusce placerat leo vel iaculis ullamcorper. Aenean facilisis arcu tellus, ut vestibulum dolor ultrices vel. Aenean eget magna varius, suscipit lacus sit amet, iaculis nisl. Quisque pharetra, nisl non condimentum ornare, metus nunc viverra augue, vitae efficitur augue neque sit amet nunc. Curabitur purus tortor, convallis a rhoncus id, sagittis ac est. Sed lacus ex, viverra finibus tristique ut, commodo id mi. Maecenas venenatis fringilla quam a pulvinar. Vestibulum bibendum eu lectus vitae sollicitudin. Integer aliquam mattis accumsan. Nullam quis nisi arcu. Praesent est dui, egestas eget iaculis quis, pulvinar in lacus. Nulla suscipit molestie massa sit amet volutpat. Suspendisse convallis urna sed mauris bibendum, eget sodales purus vulputate. Aliquam suscipit vehicula interdum. Donec quam mi, facilisis nec dui id, accumsan feugiat eros.<br>
    </p> 
    <p>   
        Aenean tempor sit amet lacus id efficitur. Donec interdum velit neque, ac aliquam elit aliquam sagittis. Nullam est eros, ultrices in malesuada eu, ornare nec nulla. Quisque sed dapibus libero. Curabitur eget rutrum neque. Ut sed scelerisque felis. Nam id lorem sed arcu accumsan eleifend. Duis quis ex facilisis, tempus lectus sed, luctus nulla. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Suspendisse potenti. Proin sodales gravida tempor. Quisque urna dolor, eleifend a lorem vel, hendrerit aliquam mi. In faucibus ipsum at velit commodo, in luctus turpis eleifend.
    </p> 
    <p>
        Donec vel auctor nibh. Vivamus imperdiet nec metus id sodales. In non finibus nisi, vel pulvinar enim. Integer vel consectetur arcu. Aliquam erat volutpat. Curabitur ac ullamcorper elit, non laoreet eros. Donec id sollicitudin enim. Morbi id lorem nunc. Quisque consequat sodales turpis in dignissim. Sed at fringilla justo. Vivamus in risus bibendum, ornare est consequat, dignissim mauris.
    </p>
    <p> 
        Nunc pulvinar elit dolor, in hendrerit mi semper sit amet. Vestibulum ultricies egestas mi suscipit suscipit. Aliquam nec urna consequat, tempus mauris in, efficitur dolor. Donec ante odio, lacinia interdum leo sit amet, commodo lacinia diam. Duis pharetra nisl quis tortor congue imperdiet. Sed sit amet elit nibh. Aliquam eget pharetra justo. Quisque pulvinar quam porta mauris congue, eget vulputate augue consequat. Suspendisse ac dui quis erat euismod tincidunt id vel dolor. Fusce urna ligula, gravida vel mattis ut, iaculis eget lacus. Sed ultricies dolor ut ex tincidunt vehicula ut quis nisi. Morbi in dignissim felis. Maecenas ac mauris urna. Duis gravida eget diam ac accumsan. Donec a sem dignissim, rutrum enim at, porta neque.
    </p>
</div>
{% endblock %}

templates/ppwstory3/posts/4.html
{% extends "ppwstory3/post_base.html" %}

{% block title %}Post4{% endblock %}

{% block date %}3 Oktober 2020{% endblock %}

{% load static %}
{% block main %}
<img alt="Illustration of random" src="{% static 'ppwstory3/img/matriks.png' %}">
<div class="maintext">
    <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean non nibh ut turpis mattis interdum eget sagittis mi. Nulla tincidunt erat at justo hendrerit, eget aliquam augue suscipit. Suspendisse dapibus rhoncus volutpat. In at nulla sed eros posuere egestas. Nullam convallis justo massa, in auctor massa fringilla id. Vestibulum ullamcorper sem libero, at hendrerit tortor blandit vel. Aliquam commodo nec nisi vel tristique. Sed efficitur eleifend nulla condimentum vulputate. Cras non nisl lorem. In feugiat metus non mi scelerisque ornare. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vestibulum rhoncus sapien vitae leo lobortis, ut venenatis quam interdum. Nam interdum est scelerisque turpis faucibus rutrum.
    </p>
    <p>
        Fusce placerat leo vel iaculis ullamcorper. Aenean facilisis arcu tellus, ut vestibulum dolor ultrices vel. Aenean eget magna varius, suscipit lacus sit amet, iaculis nisl. Quisque pharetra, nisl non condimentum ornare, metus nunc viverra augue, vitae efficitur augue neque sit amet nunc. Curabitur purus tortor, convallis a rhoncus id, sagittis ac est. Sed lacus ex, viverra finibus tristique ut, commodo id mi. Maecenas venenatis fringilla quam a pulvinar. Vestibulum bibendum eu lectus vitae sollicitudin. Integer aliquam mattis accumsan. Nullam quis nisi arcu. Praesent est dui, egestas eget iaculis quis, pulvinar in lacus. Nulla suscipit molestie massa sit amet volutpat. Suspendisse convallis urna sed mauris bibendum, eget sodales purus vulputate. Aliquam suscipit vehicula interdum. Donec quam mi, facilisis nec dui id, accumsan feugiat eros.<br>
    </p> 
    <p>   
        Aenean tempor sit amet lacus id efficitur. Donec interdum velit neque, ac aliquam elit aliquam sagittis. Nullam est eros, ultrices in malesuada eu, ornare nec nulla. Quisque sed dapibus libero. Curabitur eget rutrum neque. Ut sed scelerisque felis. Nam id lorem sed arcu accumsan eleifend. Duis quis ex facilisis, tempus lectus sed, luctus nulla. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Suspendisse potenti. Proin sodales gravida tempor. Quisque urna dolor, eleifend a lorem vel, hendrerit aliquam mi. In faucibus ipsum at velit commodo, in luctus turpis eleifend.
    </p> 
    <p>
        Donec vel auctor nibh. Vivamus imperdiet nec metus id sodales. In non finibus nisi, vel pulvinar enim. Integer vel consectetur arcu. Aliquam erat volutpat. Curabitur ac ullamcorper elit, non laoreet eros. Donec id sollicitudin enim. Morbi id lorem nunc. Quisque consequat sodales turpis in dignissim. Sed at fringilla justo. Vivamus in risus bibendum, ornare est consequat, dignissim mauris.
    </p>
    <p> 
        Nunc pulvinar elit dolor, in hendrerit mi semper sit amet. Vestibulum ultricies egestas mi suscipit suscipit. Aliquam nec urna consequat, tempus mauris in, efficitur dolor. Donec ante odio, lacinia interdum leo sit amet, commodo lacinia diam. Duis pharetra nisl quis tortor congue imperdiet. Sed sit amet elit nibh. Aliquam eget pharetra justo. Quisque pulvinar quam porta mauris congue, eget vulputate augue consequat. Suspendisse ac dui quis erat euismod tincidunt id vel dolor. Fusce urna ligula, gravida vel mattis ut, iaculis eget lacus. Sed ultricies dolor ut ex tincidunt vehicula ut quis nisi. Morbi in dignissim felis. Maecenas ac mauris urna. Duis gravida eget diam ac accumsan. Donec a sem dignissim, rutrum enim at, porta neque.
    </p>
</div>
{% endblock %}

templates/ppwstory3/profile.html
{% extends "ppwstory3/base.html" %}

{% block title %}William's Profile{% endblock %}
{% load static %}
{% block content %}
<h1>My Profile</h1>
<h2>Description</h2>
<p>I love to learn new things, but sometimes I got bored and move on to other things. Learned programming earlier in high school, but I still have much to learn.</p>
<h2>Experience</h2>
<ul>
    <li><b>...</b></li>
</ul>
<h2>Achievements</h2>
<ul>
    <li><b>...</b></li>
</ul>
<h2>Skills</h2>
<ul>
    <li><b>...</b></li>
</ul>

{% endblock %}
{% block sidebar %}
<h2>Contact</h2>
<p>Email: william92@ui.ac.id</p>
<h2>Social Media</h2>
<div style="display: inline-block; margin-bottom: 20px;">
    <img src="{% static 'ppwstory3/img/twitter.png' %}" href="https://twitter.com/hori_75" style="width: 50px; height: 50px;">
    <img alt="linkedin" src="{% static 'ppwstory1/linkedin.png' %}" href="https://www.linkedin.com/in/william-8611851a0/" style="max-width: 59px; max-height: 59px;">
</div>
{% endblock %}
{% block buttons %}
<li><a class="btn" href="{% url 'ppwstory3:index'%}">Main Page</a></li>
{% endblock %}